/**
 * Centralized blog article registry.
 * Every blog article imports its metadata from here.
 * The hub page iterates over this to render article cards.
 */

export interface BlogArticle {
  slug: string;
  title: string;
  description: string;
  category: string;
  categorySlug: string;
  datePublished: string;
  dateModified: string;
  readingTime: string;
  relatedSlugs: string[];
}

export const blogArticles: Record<string, BlogArticle> = {
  // ─── Cluster 1: Basics ───────────────────────────────────────
  'what-are-trump-accounts-guide': {
    slug: 'what-are-trump-accounts-guide',
    title: 'What Are Trump Accounts? Simple Guide',
    description: 'The complete beginner\'s guide to Trump Accounts (IRC Section 530A). Eligibility, limits, how they work, and what happens at age 18.',
    category: 'Basics',
    categorySlug: 'basics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '8 min read',
    relatedSlugs: ['who-qualifies-for-trump-account', 'how-much-money-trump-account', 'when-do-trump-accounts-start', 'is-trump-account-automatic'],
  },
  'who-qualifies-for-trump-account': {
    slug: 'who-qualifies-for-trump-account',
    title: 'Who Qualifies for a Trump Account?',
    description: 'Every U.S. citizen child under 18 with an SSN qualifies. No income limits. Learn who gets the $1,000 deposit and who does not.',
    category: 'Basics',
    categorySlug: 'basics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['do-all-babies-qualify', 'adopted-children-trump-account', 'trump-account-age-cutoff', 'what-are-trump-accounts-guide'],
  },
  'when-do-trump-accounts-start': {
    slug: 'when-do-trump-accounts-start',
    title: 'When Do Trump Accounts Start? Key Dates',
    description: 'File Form 4547 with your 2025 tax return by April 15, 2026. The trumpaccounts.gov portal launches mid-2026. Full timeline inside.',
    category: 'Basics',
    categorySlug: 'basics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['is-trump-account-automatic', 'how-to-open-step-by-step', 'what-are-trump-accounts-guide'],
  },
  'how-much-money-trump-account': {
    slug: 'how-much-money-trump-account',
    title: 'How Much Money Is in a Trump Account?',
    description: '$1,000 federal deposit for 2025-2028 births. Parents add up to $5,000/year. Employers add $2,500. See total projections.',
    category: 'Basics',
    categorySlug: 'basics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['how-much-at-age-18', 'contribution-limits-explained', 'employer-match-trump-account', 'dell-pledge-explained'],
  },
  'is-trump-account-automatic': {
    slug: 'is-trump-account-automatic',
    title: 'Is a Trump Account Automatic? (No)',
    description: 'Trump Accounts are NOT automatic. Parents must opt in by filing IRS Form 4547 with their 2025 tax return or through trumpaccounts.gov.',
    category: 'Basics',
    categorySlug: 'basics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['how-to-open-step-by-step', 'when-do-trump-accounts-start', 'what-are-trump-accounts-guide'],
  },
  'trump-account-federal-or-state': {
    slug: 'trump-account-federal-or-state',
    title: 'Are Trump Accounts Federal or State?',
    description: 'Trump Accounts are a federal program under IRC Section 530A, not a state program. Here is how they differ from state-level 529 plans.',
    category: 'Basics',
    categorySlug: 'basics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['what-are-trump-accounts-guide', 'trump-account-like-baby-savings'],
  },
  'trump-account-like-baby-savings': {
    slug: 'trump-account-like-baby-savings',
    title: 'Is a Trump Account Like a Baby Savings?',
    description: 'Trump Accounts are investment accounts, not savings accounts. Money goes into S&P 500 index funds, not a bank. Here is the difference.',
    category: 'Basics',
    categorySlug: 'basics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['how-is-trump-account-invested', 'index-fund-requirements', 'what-are-trump-accounts-guide'],
  },
  'trump-account-vs-social-security': {
    slug: 'trump-account-vs-social-security',
    title: 'Trump Account vs Social Security',
    description: 'Trump Accounts and Social Security are completely different programs. One is a child investment account; the other is retirement insurance.',
    category: 'Basics',
    categorySlug: 'basics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['what-are-trump-accounts-guide', 'trump-account-retirement-conversion'],
  },

  // ─── Cluster 2: Money & Growth ───────────────────────────────
  'how-much-at-age-18': {
    slug: 'how-much-at-age-18',
    title: 'How Much at Age 18? Trump Account Growth',
    description: 'A $1,000 deposit plus $250/month could grow to $108,000+ by age 18. See projections at different contribution levels and return rates.',
    category: 'Money & Growth',
    categorySlug: 'money-and-growth',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '6 min read',
    relatedSlugs: ['expected-returns-trump-account', 'build-50k-by-18', 'could-create-millionaires', 'contribution-limits-explained'],
  },
  'can-parents-grandparents-contribute': {
    slug: 'can-parents-grandparents-contribute',
    title: 'Can Parents & Grandparents Contribute?',
    description: 'Yes. Anyone can contribute to a Trump Account — parents, grandparents, relatives, friends. The combined annual limit is $5,000.',
    category: 'Money & Growth',
    categorySlug: 'money-and-growth',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['contribution-limits-explained', 'employer-match-trump-account', 'how-much-money-trump-account'],
  },
  'contribution-limits-explained': {
    slug: 'contribution-limits-explained',
    title: 'Trump Account Contribution Limits (2026)',
    description: '$5,000/year total from all sources. Employers can add $2,500 tax-free. Indexed for inflation after 2027. Full breakdown inside.',
    category: 'Money & Growth',
    categorySlug: 'money-and-growth',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['can-parents-grandparents-contribute', 'employer-match-trump-account', 'how-much-money-trump-account'],
  },
  'are-trump-accounts-tax-deductible': {
    slug: 'are-trump-accounts-tax-deductible',
    title: 'Are Trump Accounts Tax-Deductible? (No)',
    description: 'Contributions are after-tax. You do not get a deduction. Growth is tax-deferred. Withdrawals are taxed as ordinary income at 18+.',
    category: 'Money & Growth',
    categorySlug: 'money-and-growth',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['gains-taxation-explained', 'is-growth-tax-free', 'trump-account-roth-conversion-strategy'],
  },
  'how-is-trump-account-invested': {
    slug: 'how-is-trump-account-invested',
    title: 'How Is a Trump Account Invested?',
    description: 'All funds go into S&P 500 or broad U.S. equity index funds with expense ratios capped at 0.1%. No individual stocks or crypto.',
    category: 'Money & Growth',
    categorySlug: 'money-and-growth',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['index-fund-requirements', 'trump-account-fees-explained', 'trump-account-vs-sp500-etfs'],
  },
  'government-guarantee-returns': {
    slug: 'government-guarantee-returns',
    title: 'Does the Government Guarantee Returns?',
    description: 'No. Trump Account investments are in the stock market. Returns are not guaranteed. The government provides the $1,000 deposit, not returns.',
    category: 'Money & Growth',
    categorySlug: 'money-and-growth',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['what-happens-market-crash', 'expected-returns-trump-account', 'how-is-trump-account-invested'],
  },
  'employer-match-trump-account': {
    slug: 'employer-match-trump-account',
    title: 'Employer Match for Trump Accounts',
    description: 'Employers can contribute $2,500/year per employee, tax-free under IRC Section 128. It counts toward the $5,000 cap.',
    category: 'Money & Growth',
    categorySlug: 'money-and-growth',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['contribution-limits-explained', 'can-parents-grandparents-contribute', 'how-much-money-trump-account'],
  },

  // ─── Cluster 3: Investment Structure ─────────────────────────
  'index-fund-requirements': {
    slug: 'index-fund-requirements',
    title: 'Trump Account Index Fund Requirements',
    description: 'Funds must track the S&P 500 or a broad U.S. equity index. Expense ratios capped at 0.1%. Here are all eligible fund types.',
    category: 'Investment Structure',
    categorySlug: 'investment-structure',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['trump-account-fees-explained', 'trump-account-vs-sp500-etfs', 'how-is-trump-account-invested'],
  },
  'expected-returns-trump-account': {
    slug: 'expected-returns-trump-account',
    title: 'Expected Returns for Trump Accounts',
    description: 'Historical S&P 500 returns average 10% annually (7% after inflation). See 18-year projections at conservative, moderate, and optimistic rates.',
    category: 'Investment Structure',
    categorySlug: 'investment-structure',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '6 min read',
    relatedSlugs: ['how-much-at-age-18', 'what-happens-market-crash', 'build-50k-by-18'],
  },
  'trump-account-fees-explained': {
    slug: 'trump-account-fees-explained',
    title: 'Trump Account Fees & Expense Ratios',
    description: 'Expense ratios capped at 0.1% (10 basis points). Compare eligible ETFs like VOO (0.03%), SPY (0.09%), and IVV (0.03%).',
    category: 'Investment Structure',
    categorySlug: 'investment-structure',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['index-fund-requirements', 'trump-account-vs-sp500-etfs', 'how-is-trump-account-invested'],
  },
  'what-happens-market-crash': {
    slug: 'what-happens-market-crash',
    title: 'What Happens in a Market Crash?',
    description: 'Your Trump Account stays invested. No withdrawals before 18. Historical data shows the S&P 500 has always recovered over 18-year periods.',
    category: 'Investment Structure',
    categorySlug: 'investment-structure',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['expected-returns-trump-account', 'government-guarantee-returns', 'early-withdrawal-before-18'],
  },
  'can-parents-change-investments': {
    slug: 'can-parents-change-investments',
    title: 'Can Parents Change Trump Account Funds?',
    description: 'Parents can switch between eligible index funds during the growth phase. You cannot move to individual stocks, bonds, or crypto.',
    category: 'Investment Structure',
    categorySlug: 'investment-structure',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['index-fund-requirements', 'who-controls-trump-account', 'trump-account-vs-sp500-etfs'],
  },
  'trump-account-vs-sp500-etfs': {
    slug: 'trump-account-vs-sp500-etfs',
    title: 'Best S&P 500 ETFs for Trump Accounts',
    description: 'Compare VOO, SPY, IVV, and SPLG for Trump Accounts. Expense ratios, tracking error, and which to choose for your child.',
    category: 'Investment Structure',
    categorySlug: 'investment-structure',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '6 min read',
    relatedSlugs: ['trump-account-fees-explained', 'index-fund-requirements', 'how-is-trump-account-invested'],
  },

  // ─── Cluster 4: Use of Funds ─────────────────────────────────
  'what-can-money-be-used-for': {
    slug: 'what-can-money-be-used-for',
    title: 'What Can Trump Account Money Be Used For?',
    description: 'At 18, it converts to a traditional IRA. The money can be used for anything — college, a home, a business, or retirement savings.',
    category: 'Use of Funds',
    categorySlug: 'use-of-funds',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['trump-account-for-college', 'trump-account-for-first-home', 'trump-account-penalties', 'trump-account-retirement-conversion'],
  },
  'trump-account-for-college': {
    slug: 'trump-account-for-college',
    title: 'Can You Use a Trump Account for College?',
    description: 'Yes, but withdrawals are taxed as ordinary income (unlike a 529). Consider using both: a 529 for education and a Trump Account for everything else.',
    category: 'Use of Funds',
    categorySlug: 'use-of-funds',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['what-can-money-be-used-for', 'trump-account-fafsa-impact', 'gains-taxation-explained'],
  },
  'trump-account-for-first-home': {
    slug: 'trump-account-for-first-home',
    title: 'Trump Account for a First Home Purchase',
    description: 'At 18, Trump Account funds (now a traditional IRA) can use the $10,000 first-time homebuyer exception to avoid the 10% early withdrawal penalty.',
    category: 'Use of Funds',
    categorySlug: 'use-of-funds',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['what-can-money-be-used-for', 'trump-account-penalties', 'homeownership-impact'],
  },
  'trump-account-for-business': {
    slug: 'trump-account-for-business',
    title: 'Using a Trump Account to Start a Business',
    description: 'At 18, your child can withdraw funds for any purpose. Starting a business is an option, but withdrawals are taxed as ordinary income.',
    category: 'Use of Funds',
    categorySlug: 'use-of-funds',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['what-can-money-be-used-for', 'gains-taxation-explained', 'trump-account-penalties'],
  },
  'trump-account-for-trade-school': {
    slug: 'trump-account-for-trade-school',
    title: 'Trump Account for Trade School',
    description: 'Trump Account funds can pay for trade school, vocational training, or apprenticeships. Withdrawals are taxed but face no use restrictions.',
    category: 'Use of Funds',
    categorySlug: 'use-of-funds',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['trump-account-for-college', 'what-can-money-be-used-for', 'gains-taxation-explained'],
  },
  'trump-account-penalties': {
    slug: 'trump-account-penalties',
    title: 'Trump Account Penalties & Early Withdrawal',
    description: 'No withdrawals before 18 (except rollovers/excess/death). After 18, standard IRA rules: 10% penalty before 59.5, with exceptions.',
    category: 'Use of Funds',
    categorySlug: 'use-of-funds',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['early-withdrawal-before-18', 'gains-taxation-explained', 'what-can-money-be-used-for'],
  },
  'trump-account-retirement-conversion': {
    slug: 'trump-account-retirement-conversion',
    title: 'Trump Account to Retirement Account at 18',
    description: 'At 18, it automatically becomes a traditional IRA. Your child can also convert to a Roth IRA, paying taxes now for tax-free growth later.',
    category: 'Use of Funds',
    categorySlug: 'use-of-funds',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['trump-account-roth-conversion-strategy', 'gains-taxation-explained', 'what-can-money-be-used-for'],
  },

  // ─── Cluster 5: Eligibility Deep Dive ────────────────────────
  'do-all-babies-qualify': {
    slug: 'do-all-babies-qualify',
    title: 'Do All Babies Qualify for Trump Accounts?',
    description: 'All U.S. citizen babies with an SSN qualify. But the $1,000 deposit is only for 2025-2028 births. Parents must opt in.',
    category: 'Eligibility',
    categorySlug: 'eligibility',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['who-qualifies-for-trump-account', 'already-born-children', 'is-trump-account-automatic'],
  },
  'already-born-children': {
    slug: 'already-born-children',
    title: 'Trump Accounts for Already-Born Children',
    description: 'Children born before 2025 can open a Trump Account if under 18. They won\'t get the $1,000 deposit but can receive family contributions.',
    category: 'Eligibility',
    categorySlug: 'eligibility',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['do-all-babies-qualify', 'trump-account-age-cutoff', 'who-qualifies-for-trump-account'],
  },
  'adopted-children-trump-account': {
    slug: 'adopted-children-trump-account',
    title: 'Trump Accounts for Adopted Children',
    description: 'Adopted U.S. citizen children with a valid SSN qualify on the same terms. Citizenship and SSN are what matter, not biological relationship.',
    category: 'Eligibility',
    categorySlug: 'eligibility',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['who-qualifies-for-trump-account', 'do-all-babies-qualify', 'undocumented-families-trump-account'],
  },
  'undocumented-families-trump-account': {
    slug: 'undocumented-families-trump-account',
    title: 'Trump Accounts for Mixed-Status Families',
    description: 'The child must be a U.S. citizen with an SSN. If the child qualifies but a parent is undocumented, filing options depend on tax ID status.',
    category: 'Eligibility',
    categorySlug: 'eligibility',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['who-qualifies-for-trump-account', 'adopted-children-trump-account', 'how-to-open-step-by-step'],
  },
  'moving-abroad-trump-account': {
    slug: 'moving-abroad-trump-account',
    title: 'What Happens if You Move Abroad?',
    description: 'The account stays open. U.S. citizenship is what matters, not residence. Foreign tax implications may apply depending on the country.',
    category: 'Eligibility',
    categorySlug: 'eligibility',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['who-qualifies-for-trump-account', 'who-controls-trump-account', 'gains-taxation-explained'],
  },
  'trump-account-age-cutoff': {
    slug: 'trump-account-age-cutoff',
    title: 'Trump Account Age Cutoff & Eligibility',
    description: 'Children must be under 18 at the end of the election year. A 17-year-old can still open one but will have limited growth time.',
    category: 'Eligibility',
    categorySlug: 'eligibility',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['already-born-children', 'who-qualifies-for-trump-account', 'do-all-babies-qualify'],
  },

  // ─── Cluster 6: Control & Access ─────────────────────────────
  'who-controls-trump-account': {
    slug: 'who-controls-trump-account',
    title: 'Who Controls a Trump Account Before 18?',
    description: 'The authorized individual (parent or legal guardian) manages the account. At 18, full control transfers to the child.',
    category: 'Control & Access',
    categorySlug: 'control-and-access',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['can-parents-change-investments', 'trump-account-divorce', 'early-withdrawal-before-18'],
  },
  'early-withdrawal-before-18': {
    slug: 'early-withdrawal-before-18',
    title: 'Can You Withdraw Before 18? (No)',
    description: 'Withdrawals before 18 are not allowed except for rollovers, return of excess contributions, or death of the beneficiary.',
    category: 'Control & Access',
    categorySlug: 'control-and-access',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['trump-account-penalties', 'who-controls-trump-account', 'what-happens-market-crash'],
  },
  'trump-account-divorce': {
    slug: 'trump-account-divorce',
    title: 'Trump Accounts and Divorce',
    description: 'Trump Accounts belong to the child, not the parents. Divorce does not change the account. Custody may affect who is the authorized individual.',
    category: 'Control & Access',
    categorySlug: 'control-and-access',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['who-controls-trump-account', 'trump-account-debt-seizure', 'early-withdrawal-before-18'],
  },
  'trump-account-disability': {
    slug: 'trump-account-disability',
    title: 'Trump Accounts and Disability',
    description: 'Standard IRA disability exceptions apply after age 18. Before 18, the account follows standard Trump Account rules with limited exceptions.',
    category: 'Control & Access',
    categorySlug: 'control-and-access',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['trump-account-penalties', 'trump-account-medicaid-impact', 'early-withdrawal-before-18'],
  },
  'trump-account-debt-seizure': {
    slug: 'trump-account-debt-seizure',
    title: 'Can Creditors Seize a Trump Account?',
    description: 'During the growth phase, Trump Account protections are similar to IRA protections. After 18, standard IRA creditor rules apply by state.',
    category: 'Control & Access',
    categorySlug: 'control-and-access',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['who-controls-trump-account', 'trump-account-divorce', 'trump-account-penalties'],
  },
  'trump-account-death-of-child': {
    slug: 'trump-account-death-of-child',
    title: 'What Happens if the Child Dies?',
    description: 'Funds can be distributed to the estate or designated beneficiary. IRS Notice 2025-68 specifically addresses this scenario.',
    category: 'Control & Access',
    categorySlug: 'control-and-access',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '3 min read',
    relatedSlugs: ['who-controls-trump-account', 'early-withdrawal-before-18', 'what-are-trump-accounts-guide'],
  },

  // ─── Cluster 7: Tax Questions ────────────────────────────────
  'gains-taxation-explained': {
    slug: 'gains-taxation-explained',
    title: 'How Are Trump Account Gains Taxed?',
    description: 'Growth is tax-deferred. Withdrawals after 18 are taxed as ordinary income. Before 59.5, a 10% early withdrawal penalty also applies.',
    category: 'Tax Questions',
    categorySlug: 'tax-questions',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['is-growth-tax-free', 'trump-account-roth-conversion-strategy', 'trump-account-penalties'],
  },
  'is-growth-tax-free': {
    slug: 'is-growth-tax-free',
    title: 'Is Trump Account Growth Tax-Free? (No)',
    description: 'Growth is tax-deferred, not tax-free. You pay ordinary income tax on withdrawals. This is traditional IRA treatment, not Roth treatment.',
    category: 'Tax Questions',
    categorySlug: 'tax-questions',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['gains-taxation-explained', 'are-trump-accounts-tax-deductible', 'trump-account-roth-conversion-strategy'],
  },
  'trump-account-fafsa-impact': {
    slug: 'trump-account-fafsa-impact',
    title: 'Does a Trump Account Affect FAFSA?',
    description: 'As a child-owned IRA at 18, it may be reported as a student asset on FAFSA, which could reduce financial aid eligibility.',
    category: 'Tax Questions',
    categorySlug: 'tax-questions',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['trump-account-for-college', 'gains-taxation-explained', 'trump-account-medicaid-impact'],
  },
  'trump-account-medicaid-impact': {
    slug: 'trump-account-medicaid-impact',
    title: 'Does a Trump Account Affect Medicaid?',
    description: 'During the growth phase (under 18), Trump Accounts may not count as an asset. After 18 as an IRA, Medicaid asset rules vary by state.',
    category: 'Tax Questions',
    categorySlug: 'tax-questions',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '4 min read',
    relatedSlugs: ['trump-account-fafsa-impact', 'gains-taxation-explained', 'trump-account-disability'],
  },
  'trump-account-roth-conversion-strategy': {
    slug: 'trump-account-roth-conversion-strategy',
    title: 'Roth Conversion Strategy at 18',
    description: 'Converting the traditional IRA to a Roth IRA while in a low tax bracket at 18 could save thousands in future taxes. Here is the math.',
    category: 'Tax Questions',
    categorySlug: 'tax-questions',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '6 min read',
    relatedSlugs: ['gains-taxation-explained', 'is-growth-tax-free', 'trump-account-retirement-conversion'],
  },

  // ─── Cluster 8: Policy & Economics ───────────────────────────
  'cost-to-taxpayers': {
    slug: 'cost-to-taxpayers',
    title: 'How Much Do Trump Accounts Cost Taxpayers?',
    description: 'The pilot program costs billions over 4 years for the $1,000 deposits. Here is how the numbers break down by birth cohort.',
    category: 'Policy & Economics',
    categorySlug: 'policy-and-economics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['national-debt-impact', 'economic-impact', 'dell-pledge-explained'],
  },
  'national-debt-impact': {
    slug: 'national-debt-impact',
    title: 'Trump Accounts and the National Debt',
    description: 'The pilot deposit adds to federal spending, but long-term wealth creation could reduce government dependency over decades.',
    category: 'Policy & Economics',
    categorySlug: 'policy-and-economics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['cost-to-taxpayers', 'economic-impact', 'wealth-creation-potential'],
  },
  'economic-impact': {
    slug: 'economic-impact',
    title: 'Economic Impact of Trump Accounts',
    description: 'Giving every child a financial head start could boost homeownership, entrepreneurship, and retirement readiness across generations.',
    category: 'Policy & Economics',
    categorySlug: 'policy-and-economics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '6 min read',
    relatedSlugs: ['wealth-creation-potential', 'homeownership-impact', 'inequality-reduction'],
  },
  'wealth-creation-potential': {
    slug: 'wealth-creation-potential',
    title: 'Trump Accounts and Wealth Creation',
    description: 'Compounding $1,000 over 18 years at historical S&P 500 returns creates $4,000-$6,000. With family contributions, much more.',
    category: 'Policy & Economics',
    categorySlug: 'policy-and-economics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['how-much-at-age-18', 'could-create-millionaires', 'economic-impact'],
  },
  'inequality-reduction': {
    slug: 'inequality-reduction',
    title: 'Can Trump Accounts Reduce Inequality?',
    description: 'Universal accounts help, but wealthier families benefit more from the $5,000 limit. The Dell pledge targets lower-income ZIP codes.',
    category: 'Policy & Economics',
    categorySlug: 'policy-and-economics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['wealth-gap-impact', 'dell-pledge-explained', 'economic-impact'],
  },
  'homeownership-impact': {
    slug: 'homeownership-impact',
    title: 'Trump Accounts and Homeownership',
    description: 'A $50K-$100K+ IRA at 18 could serve as a down payment fund. The first-time homebuyer IRA exception avoids the 10% penalty on $10,000.',
    category: 'Policy & Economics',
    categorySlug: 'policy-and-economics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['trump-account-for-first-home', 'economic-impact', 'how-much-at-age-18'],
  },
  'dell-pledge-explained': {
    slug: 'dell-pledge-explained',
    title: 'The Dell $6.25 Billion Pledge Explained',
    description: 'Michael and Susan Dell pledged $250 per child under 10 in ZIP codes below $150K median income. Here is how it works and who qualifies.',
    category: 'Policy & Economics',
    categorySlug: 'policy-and-economics',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['how-much-money-trump-account', 'inequality-reduction', 'what-are-trump-accounts-guide'],
  },

  // ─── Cluster 9: Practical Parent Guides ──────────────────────
  'how-to-open-step-by-step': {
    slug: 'how-to-open-step-by-step',
    title: 'How to Open a Trump Account (2026)',
    description: 'Step-by-step: get your child\'s SSN, download Form 4547, file with your taxes or through trumpaccounts.gov. Full walkthrough.',
    category: 'Parent Guides',
    categorySlug: 'parent-guides',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '6 min read',
    relatedSlugs: ['is-trump-account-automatic', 'when-do-trump-accounts-start', 'who-qualifies-for-trump-account'],
  },
  'should-i-wait-or-invest-now': {
    slug: 'should-i-wait-or-invest-now',
    title: 'Wait or Invest Now in a Trump Account?',
    description: 'File Form 4547 now. Time in the market beats timing the market. Every month of delay reduces 18-year compounding.',
    category: 'Parent Guides',
    categorySlug: 'parent-guides',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['how-much-at-age-18', 'expected-returns-trump-account', 'how-to-open-step-by-step'],
  },
  'replicate-trump-account-yourself': {
    slug: 'replicate-trump-account-yourself',
    title: 'DIY Trump Account: Replicate It Yourself',
    description: 'If your child doesn\'t qualify for the $1,000 deposit, replicate the strategy with a custodial account and an S&P 500 index fund.',
    category: 'Parent Guides',
    categorySlug: 'parent-guides',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '6 min read',
    relatedSlugs: ['index-fund-requirements', 'trump-account-vs-sp500-etfs', 'best-accounts-for-kids-today'],
  },
  'build-50k-by-18': {
    slug: 'build-50k-by-18',
    title: 'How to Build $50,000 by Age 18',
    description: 'Contributing $200/month to a Trump Account at 8% average returns reaches $50K by 18. Here is the exact math and contribution schedule.',
    category: 'Parent Guides',
    categorySlug: 'parent-guides',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '5 min read',
    relatedSlugs: ['how-much-at-age-18', 'contribution-limits-explained', 'expected-returns-trump-account'],
  },
  'best-accounts-for-kids-today': {
    slug: 'best-accounts-for-kids-today',
    title: 'Best Investment Accounts for Kids (2026)',
    description: 'Comparing Trump Accounts, 529s, custodial accounts, Roth IRAs, and Coverdell ESAs. Which ones should you open? Our recommendation.',
    category: 'Parent Guides',
    categorySlug: 'parent-guides',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '7 min read',
    relatedSlugs: ['replicate-trump-account-yourself', 'what-are-trump-accounts-guide', 'should-i-wait-or-invest-now'],
  },

  // ─── Cluster 10: Analysis / Viral ────────────────────────────
  'could-create-millionaires': {
    slug: 'could-create-millionaires',
    title: 'Could Trump Accounts Create Millionaires?',
    description: 'If the $1,000 deposit grows untouched to age 65, historical S&P 500 returns suggest it could reach $1M+. Full projection inside.',
    category: 'Analysis',
    categorySlug: 'analysis',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '6 min read',
    relatedSlugs: ['how-much-at-age-18', 'expected-returns-trump-account', 'wealth-creation-potential'],
  },
  'every-baby-by-2045': {
    slug: 'every-baby-by-2045',
    title: 'How Much Every Baby Would Have by 2045',
    description: 'A child born in 2025 with the $1,000 deposit and $250/month contributions could have $100K+ by 2045. We project every scenario.',
    category: 'Analysis',
    categorySlug: 'analysis',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '6 min read',
    relatedSlugs: ['how-much-at-age-18', 'could-create-millionaires', 'build-50k-by-18'],
  },
  'wealth-gap-impact': {
    slug: 'wealth-gap-impact',
    title: 'Trump Accounts and the Wealth Gap',
    description: 'Universal child accounts could narrow the racial wealth gap, but contribution capacity favors higher-income families. Full analysis.',
    category: 'Analysis',
    categorySlug: 'analysis',
    datePublished: '2026-02-12',
    dateModified: '2026-02-12',
    readingTime: '7 min read',
    relatedSlugs: ['inequality-reduction', 'dell-pledge-explained', 'economic-impact'],
  },
};

/** Get all articles for a given category slug. */
export function getArticlesByCategory(categorySlug: string): BlogArticle[] {
  return Object.values(blogArticles).filter(a => a.categorySlug === categorySlug);
}

/** Get all unique categories with article counts. */
export function getAllCategories(): { name: string; slug: string; count: number }[] {
  const map = new Map<string, { name: string; count: number }>();
  for (const article of Object.values(blogArticles)) {
    const existing = map.get(article.categorySlug);
    if (existing) {
      existing.count++;
    } else {
      map.set(article.categorySlug, { name: article.category, count: 1 });
    }
  }
  return Array.from(map.entries()).map(([slug, { name, count }]) => ({ name, slug, count }));
}

/** Get related articles for a given article slug. */
export function getRelatedArticles(slug: string): BlogArticle[] {
  const article = blogArticles[slug];
  if (!article) return [];
  return article.relatedSlugs
    .map(s => blogArticles[s])
    .filter((a): a is BlogArticle => !!a);
}

/** Get a single article by slug. */
export function getArticle(slug: string): BlogArticle | undefined {
  return blogArticles[slug];
}

/** Get total article count. */
export function getArticleCount(): number {
  return Object.keys(blogArticles).length;
}
